name: Deploy

on:
  push:
    branches: [ main ]

concurrency:
  group: environment-${{ github.ref }}

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    
    - name: Setup NodeJS 😞
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    
    - uses: actions/cache@v2.1.6
      with:
        path: 'node_modules'
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies 🔧
      run: |
        npm install

    - name: Build App 
      env:
        # blank string because apparently false doesn't work and we want to ignore react warnings
        CI: ""
      run: |
        npm run build

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: build # The folder the action should deploy.